# Generated by Django 4.0.2 on 2022-02-23 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.FloatField(default=0)),
                ('percantage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EulerProblem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('code_lines', models.IntegerField()),
                ('description', models.TextField()),
                ('solution', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.FloatField(default=0)),
                ('assets', models.IntegerField(default=0)),
                ('chart', models.ImageField(blank=True, null=True, upload_to='static/img')),
                ('profitability', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('standartandpoor', models.ImageField(blank=True, null=True, upload_to='')),
                ('revenue_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('exchange', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('buy_price', models.FloatField(default=0)),
                ('curent_price', models.FloatField(blank=True, null=True)),
                ('dividend', models.FloatField(blank=True, null=True)),
                ('poe', models.FloatField(default=1)),
                ('amount', models.IntegerField(default=1)),
                ('share', models.FloatField(blank=True, null=True)),
                ('invested', models.FloatField(blank=True, null=True)),
                ('end_value', models.FloatField(blank=True, null=True)),
                ('profit', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(-1, 'Не нравится'), (1, 'Нравится')], verbose_name='Голос')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainsite.post')),
            ],
        ),
    ]
