# Generated by Django 4.0.2 on 2022-02-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_codeexamples_deposit_eulerproblem_portfolio_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
