# Generated by Django 4.0.2 on 2022-02-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_codeexamples_deposit_eulerproblem_portfolio_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='invested',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
