# Generated by Django 4.0.2 on 2022-02-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_portfolio_invested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='invested',
            field=models.FloatField(default=0),
        ),
    ]
