# Generated by Django 3.2.8 on 2021-10-29 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20211028_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
