# Generated by Django 3.2.8 on 2021-11-03 05:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainsite', '0008_post_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='post',
            name='is_liked',
            field=models.ManyToManyField(default=False, related_name='is_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
