# Generated by Django 3.2.8 on 2022-02-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='dividend',
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='new_price',
            field=models.FloatField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='poe',
            field=models.FloatField(default=1),
        ),
    ]
