# Generated by Django 3.2.8 on 2022-02-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_auto_20220217_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='invested',
            field=models.FloatField(default=0),
        ),
    ]
