# Generated by Django 3.2.8 on 2022-02-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20220217_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
