# Generated by Django 3.2.8 on 2022-02-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_stock_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='invested',
        ),
    ]
