# Generated by Django 3.2.8 on 2022-02-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_remove_stock_invested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='new_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='curent_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='invested',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='share',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='dividend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
