# Generated by Django 3.2.8 on 2022-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_auto_20220217_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='profit',
            field=models.FloatField(default=0),
        ),
    ]
