# Generated by Django 3.2.8 on 2022-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_stock_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='end_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
