# Generated by Django 3.2.8 on 2022-02-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0021_stock_end_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.FloatField()),
                ('assets', models.IntegerField()),
                ('chart', models.ImageField(upload_to='')),
                ('profitability', models.FloatField()),
                ('profit', models.FloatField()),
                ('standartandpoor', models.ImageField(upload_to='')),
                ('revenue_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
