# Generated by Django 3.2.8 on 2022-02-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0022_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='chart',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='revenue_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='standartandpoor',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
