# Generated by Django 3.2.8 on 2022-02-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0023_auto_20220217_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='assets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='capital',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='profitability',
            field=models.FloatField(default=0),
        ),
    ]
