# Generated by Django 3.2.8 on 2022-02-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0024_auto_20220217_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='asset_type',
            field=models.CharField(default='assets', max_length=20),
        ),
    ]
