# Generated by Django 3.2.8 on 2022-02-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0025_portfolio_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='asset_type',
            field=models.CharField(choices=[('S', 'Stock'), ('E', 'ETF'), ('D', 'Deposit'), ('C', 'Crypto'), ('B', 'Bonds'), ('I', 'Index')], max_length=1),
        ),
    ]
